CREATE TABLE "APP_CONTROL_MODULE"."AppUpdate"
(
  "Id" NVARCHAR2(36) NOT NULL ENABLE,
  "VersionCode" NVARCHAR2(50) NOT NULL ENABLE,
  "VersionName" NVARCHAR2(50) NOT NULL ENABLE,
  "IsForcedUpdate" NUMBER(1,0) DEFAULT (0) NOT NULL ENABLE,
  "IsNewVersionAvailable" NUMBER(1,0) DEFAULT (0) NOT NULL ENABLE,
  "Platform" NVARCHAR2(50) NOT NULL ENABLE,
  "UpdateDate" TIMESTAMP (6) DEFAULT (CURRENT_TIMESTAMP) NOT NULL ENABLE,
  "InsertDate" TIMESTAMP (6) NOT NULL ENABLE,
  "Version" RAW(2000) DEFAULT HEXTORAW('') NOT NULL ENABLE,
  "InsertUser" NVARCHAR2(2000) NOT NULL ENABLE,
  "UpdateUser" NVARCHAR2(2000) NOT NULL ENABLE,
  CONSTRAINT "PK_AppUpdate" PRIMARY KEY ("Id")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "USERS" ENABLE
)
SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS";

CREATE INDEX "APP_CONTROL_MODULE"."IX_AppUpdate_IsForcedUpdate"
ON "APP_CONTROL_MODULE"."AppUpdate" ("IsForcedUpdate")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
TABLESPACE "USERS";

CREATE INDEX "APP_CONTROL_MODULE"."IX_AppUpdate_IsNewVersionAvailable"
ON "APP_CONTROL_MODULE"."AppUpdate" ("IsNewVersionAvailable")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
TABLESPACE "USERS";

CREATE INDEX "APP_CONTROL_MODULE"."IX_AppUpdate_Platform"
ON "APP_CONTROL_MODULE"."AppUpdate" ("Platform")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
TABLESPACE "USERS";

CREATE UNIQUE INDEX "APP_CONTROL_MODULE"."IX_AppUpdate_VersionCode"
ON "APP_CONTROL_MODULE"."AppUpdate" ("VersionCode")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
TABLESPACE "USERS";

CREATE OR REPLACE EDITIONABLE TRIGGER "APP_CONTROL_MODULE"."rowversion_AppUpdate"
BEFORE INSERT OR UPDATE ON "APP_CONTROL_MODULE"."AppUpdate"
FOR EACH ROW
BEGIN
  :NEW."Version" := UTL_RAW.CAST_FROM_BINARY_INTEGER(
    UTL_RAW.CAST_TO_BINARY_INTEGER(NVL(:OLD."Version", '00000000')) + 1
  );
END;
/

ALTER TRIGGER "APP_CONTROL_MODULE"."rowversion_AppUpdate" ENABLE;
