CREATE TABLE "APP_CONTROL_MODULE"."ThirdPartyServiceConfig"
(
  "Id" NVARCHAR2(100) NOT NULL ENABLE,
  "ServiceName" NVARCHAR2(100) NOT NULL ENABLE,
  "DisplayName" NVARCHAR2(200) NOT NULL ENABLE,
  "GLAccount" NVARCHAR2(50) NOT NULL ENABLE,
  "BranchCode" NVARCHAR2(20) NOT NULL ENABLE,
  "Currency" NVARCHAR2(10) NOT NULL ENABLE,
  "ServiceCategory" NVARCHAR2(50) NOT NULL ENABLE,
  "IsEnabled" NUMBER(10,0) NOT NULL ENABLE,
  "Status" NVARCHAR2(30) NOT NULL ENABLE,
  "ConfigParams" NVARCHAR2(2000),
  "Description" NVARCHAR2(500),
  "CreatedAt" TIMESTAMP (7) NOT NULL ENABLE,
  "UpdatedAt" TIMESTAMP (7) NOT NULL ENABLE,
  "CreatedBy" NVARCHAR2(50) NOT NULL ENABLE,
  "UpdatedBy" NVARCHAR2(50) NOT NULL ENABLE,
  "Version" RAW(8),
  CONSTRAINT "PK_ThirdPartyServiceConfig" PRIMARY KEY ("Id")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "USERS" ENABLE
)
SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS";

CREATE OR REPLACE EDITIONABLE TRIGGER "APP_CONTROL_MODULE"."rowversion_ThirdPartyServiceConfig"
BEFORE INSERT OR UPDATE ON "APP_CONTROL_MODULE"."ThirdPartyServiceConfig"
FOR EACH ROW
BEGIN
  :NEW."Version" := UTL_RAW.CAST_FROM_BINARY_INTEGER(
    UTL_RAW.CAST_TO_BINARY_INTEGER(NVL(:OLD."Version", '00000000')) + 1
  );
END;
/

ALTER TRIGGER "APP_CONTROL_MODULE"."rowversion_ThirdPartyServiceConfig" ENABLE;
